# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Create the orb for the code coverage upload
orbs:
  codecov: codecov/codecov@3.2.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  miseq_hashr:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: ubuntu:20.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Setup Environment and Run Tests
          command: |
            apt update
            apt install -y wget coreutils curl gnupg pip
            pip install pytest pytest-cov
            python -m pytest tests/ -s -vvv --cov=hashr --cov-report term-missing --cov-config=.coveragec --cov-report=xml:test_reports/miseq_hashr.xml
      - store_artifacts:
          path: test_reports/
          destination: circleci-docs
      - codecov/upload:
          file: /root/project/test_reports/miseq_hashr.xml
          xtra_args: -R /root/project/
workflows:
    build_and_test:
        jobs:
          - miseq_hashr:
              filters:
                branches:
                  ignore: gh-pages